store: sandag.h5

urbancanvas: False

aggregation_tables:
  - nodes

set_nan_price_to_zero: True


remove_invalid_building_ids: True


reconcile_residential_units_and_households: True


reconcile_non_residential_sqft_and_jobs: True


set_nan_price_to_zero: True


rates:
  households_relocation: .005
  jobs_relocation: .005
  simple_households_transition: .01
  simple_jobs_transition: .01


build_networks:
  name: osm_sandag.h5
  max_distance: 1500


households_transition:
  add_columns:
    - income_quartile
  total_column: total_number_of_households


jobs_transition:
  add_columns:
    - empsix_id
  total_column: number_of_jobs


feasibility:
  parcel_filter: newest_building < 2010
  residential_to_yearly: True
  pass_through:
    - oldest_building
    - newest_building
    - total_sqft
    - max_far
    - max_dua
    - land_cost
    - residential
    - min_max_fars
    - max_far_from_dua
    - max_height
    - max_far_from_heights
    - building_purchase_price
    - building_purchase_price_sqft


residential_developer:
  target_vacancy: .10
  min_unit_size: 1000
  bldg_sqft_per_job: 400


non_residential_developer:
  target_vacancy: .21
  bldg_sqft_per_job: 400

scenario: baseline


# this maps building "forms" from the developer model
# to building types so that when the developer builds a
# "form" this can be converted for storing as a type
# in the building table - in the long run, the developer
# forms and the building types should be the same and the
# developer model should account for the differences
form_to_btype:
  residential:
    - 19
    - 20
    - 21
  industrial:
    - 2
    - 3
  retail:
    - 5
  office:
    - 4
  mixedresidential:
    - 1
  mixedoffice:
    - 6


building_sqft_per_job:
  -1: 400
  1: 400
  2: 400
  3: 400
  4: 355
  5: 1161
  6: 470
  7: 661
  8: 960
  9: 825
  10: 445
  11: 445
  12: 383
  13: 383
  14: 383
  
# this maps building type ids to general building types
# basically just reduces dimensionality
building_type_map:
  1: Other
  2: Industrial
  3: Industrial
  4: Office
  5: Retail
  6: Other
  7: Other
  8: Other
  9: Other
  10: Other
  11: Other
  12: Other
  13: Other
  14: Other
  15: Other
  16: Other
  17: Other
  18: Other
  19: Residential
  20: Residential
  21: Residential
  22: Other
  23: Other
  24: Other
  25: Other
  26: Other
  27: Other
  28: Other
  29: Other
  30: Other
  31: Other
